# Generated by Django 4.2.6 on 2023-10-20 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'buyer',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('description', models.TextField(null=True)),
                ('start_price', models.FloatField()),
                ('lowest_price', models.FloatField()),
                ('bought', models.BooleanField(default=False)),
                ('image', models.ImageField(null=True, upload_to='images/')),
            ],
            options={
                'db_table': 'item',
                'managed': True,
            },
        ),
    ]
