# Generated by Django 4.2.6 on 2023-10-20 01:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('accepted', models.BooleanField(default=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sale.buyer')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sale.item')),
            ],
            options={
                'db_table': 'offer',
                'managed': True,
            },
        ),
    ]
