# Generated by Django 4.2.6 on 2023-11-15 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0002_offer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('date', models.DateField(auto_now_add=True)),
                ('voucher', models.FileField(upload_to='files/')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sale.buyer')),
            ],
            options={
                'db_table': 'payment',
                'managed': True,
            },
        ),
    ]
